### ISSUE TITLE
TypeError: this._evictSession is not a function

### ISSUE THREAD

**Issue by fengmk2** [node-modules/agentkeepalive#34]
```
TypeError: this._evictSession is not a function
    at TLSSocket.<anonymous> (https.js:90:12)
    at TLSSocket.g (events.js:273:16)
    at emitOne (events.js:95:20)
    at TLSSocket.emit (events.js:182:7)
    at TCP._onclose (net.js:471:12)
```

**Comment by fengmk2** [comment]
https://github.com/nodejs/node/commit/165b33fce2ed26e969beed3d3f7796708f0743e1

**Comment by fengmk2** [comment]
https://github.com/nodejs/node/blame/165b33fce2ed26e969beed3d3f7796708f0743e1/lib/https.js#L174

**Comment by fengmk2** [comment]
https://github.com/nodejs/node/blob/master/lib/https.js#L174

**Comment by fengmk2** [comment]
https://github.com/nodejs/node/blob/v4.x/lib/https.js#L162
